=== Craftarc/axel/docs/data-contracts/aws-lambda/response.schema.json
{
  "$schema": "http://json-schema.org/2020-12/schema",
  "$ref": "#/definitions/Response",
  "definitions": {
	"Response": {
	  "type": "object",
	  "additionalProperties": false,
	  "properties": {
		"version": {
		  "type": "string"
		},
		"routeKey": {
		  "type": "string"
		},
		"rawPath": {
		  "type": "string"
		},
		"rawQueryString": {
		  "type": "string"
		},
		"headers": {
		  "$ref": "#/definitions/Headers"
		},
		"queryStringParameters": {
		  "$ref": "#/definitions/QueryStringParameters"
		},
		"requestContext": {
		  "$ref": "#/definitions/RequestContext"
		},
		"isBase64Encoded": {
		  "type": "boolean"
		}
	  },
	  "required": [
		"headers",
		"isBase64Encoded",
		"queryStringParameters",
		"rawPath",
		"rawQueryString",
		"requestContext",
		"routeKey",
		"version"
	  ],
	  "title": "Response"
	},
	"Headers": {
	  "type": "object",
	  "additionalProperties": false,
	  "properties": {
		"sec-fetch-mode": {
		  "type": "string"
		},
		"referer": {
		  "type": "string",
		  "format": "uri",
		  "qt-uri-protocols": [
			"https"
		  ]
		},
		"x-amzn-tls-version": {
		  "type": "string"
		},
		"sec-fetch-site": {
		  "type": "string"
		},
		"accept-language": {
		  "type": "string"
		},
		"x-forwarded-proto": {
		  "type": "string"
		},
		"x-forwarded-port": {
		  "type": "string",
		  "format": "integer"
		},
		"x-forwarded-for": {
		  "type": "string"
		},
		"sec-fetch-user": {
		  "type": "string"
		},
		"accept": {
		  "type": "string"
		},
		"x-amzn-tls-cipher-suite": {
		  "type": "string"
		},
		"sec-ch-ua": {
		  "type": "string"
		},
		"sec-ch-ua-mobile": {
		  "type": "string"
		},
		"x-amzn-trace-id": {
		  "type": "string"
		},
		"sec-ch-ua-platform": {
		  "type": "string"
		},
		"host": {
		  "type": "string"
		},
		"upgrade-insecure-requests": {
		  "type": "string",
		  "format": "integer"
		},
		"cache-control": {
		  "type": "string"
		},
		"accept-encoding": {
		  "type": "string"
		},
		"sec-fetch-dest": {
		  "type": "string"
		},
		"user-agent": {
		  "type": "string"
		}
	  },
	  "required": [
		"accept",
		"accept-encoding",
		"accept-language",
		"cache-control",
		"host",
		"referer",
		"sec-ch-ua",
		"sec-ch-ua-mobile",
		"sec-ch-ua-platform",
		"sec-fetch-dest",
		"sec-fetch-mode",
		"sec-fetch-site",
		"sec-fetch-user",
		"upgrade-insecure-requests",
		"user-agent",
		"x-amzn-tls-cipher-suite",
		"x-amzn-tls-version",
		"x-amzn-trace-id",
		"x-forwarded-for",
		"x-forwarded-port",
		"x-forwarded-proto"
	  ],
	  "title": "Headers"
	},
	"QueryStringParameters": {
	  "type": "object",
	  "additionalProperties": false,
	  "properties": {
		"code": {
		  "type": "string"
		},
		"state": {
		  "type": "string"
		}
	  },
	  "required": [
		"code",
		"state"
	  ],
	  "title": "QueryStringParameters"
	},
	"RequestContext": {
	  "type": "object",
	  "additionalProperties": false,
	  "properties": {
		"accountId": {
		  "type": "string"
		},
		"apiId": {
		  "type": "string"
		},
		"domainName": {
		  "type": "string"
		},
		"domainPrefix": {
		  "type": "string"
		},
		"http": {
		  "$ref": "#/definitions/HTTP"
		},
		"requestId": {
		  "type": "string",
		  "format": "uuid"
		},
		"routeKey": {
		  "type": "string"
		},
		"stage": {
		  "type": "string"
		},
		"time": {
		  "type": "string"
		},
		"timeEpoch": {
		  "type": "integer"
		}
	  },
	  "required": [
		"accountId",
		"apiId",
		"domainName",
		"domainPrefix",
		"http",
		"requestId",
		"routeKey",
		"stage",
		"time",
		"timeEpoch"
	  ],
	  "title": "RequestContext"
	},
	"HTTP": {
	  "type": "object",
	  "additionalProperties": false,
	  "properties": {
		"method": {
		  "type": "string"
		},
		"path": {
		  "type": "string"
		},
		"protocol": {
		  "type": "string"
		},
		"sourceIp": {
		  "type": "string"
		},
		"userAgent": {
		  "type": "string"
		}
	  },
	  "required": [
		"method",
		"path",
		"protocol",
		"sourceIp",
		"userAgent"
	  ],
	  "title": "HTTP"
	}
  }
}

=== Craftarc/axel/docs/data-contracts/aws-lambda/sample-response.json
{
  "version": "2.0",
  "routeKey": "$default",
  "rawPath": "/",
  "rawQueryString": "code=ee2bf05af34e72c404d9ead42c47f493c8e56590&state=b3YkJi8YYnraGKZgDIHavPGHaybR-pWM__CSrrjPFmA",
  "headers": {
	"sec-fetch-mode": "navigate",
	"referer": "https://www.pathofexile.com/",
	"x-amzn-tls-version": "TLSv1.2",
	"sec-fetch-site": "cross-site",
	"accept-language": "en-US,en;q=0.9",
	"x-forwarded-proto": "https",
	"x-forwarded-port": "443",
	"x-forwarded-for": "116.14.157.253",
	"sec-fetch-user": "?1",
	"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
	"x-amzn-tls-cipher-suite": "ECDHE-RSA-AES128-GCM-SHA256",
	"sec-ch-ua": "\"Not.A/Brand\";v=\"8\", \"Chromium\";v=\"114\", \"Google Chrome\";v=\"114\"",
	"sec-ch-ua-mobile": "?0",
	"x-amzn-trace-id": "Root=1-64b3a605-6d64e9703d320a4d63ba706c",
	"sec-ch-ua-platform": "\"Windows\"",
	"host": "bibdsedr7muzq2hg5h2rqzs2ke0matoa.lambda-url.us-west-1.on.aws",
	"upgrade-insecure-requests": "1",
	"cache-control": "max-age=0",
	"accept-encoding": "gzip, deflate, br",
	"sec-fetch-dest": "document",
	"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
  },
  "queryStringParameters": {
	"code": "ee2bf05af34e72c404d9ead42c47f493c8e56590",
	"state": "b3YkJi8YYnraGKZgDIHavPGHaybR-pWM__CSrrjPFmA"
  },
  "requestContext": {
	"accountId": "anonymous",
	"apiId": "bibdsedr7muzq2hg5h2rqzs2ke0matoa",
	"domainName": "bibdsedr7muzq2hg5h2rqzs2ke0matoa.lambda-url.us-west-1.on.aws",
	"domainPrefix": "bibdsedr7muzq2hg5h2rqzs2ke0matoa",
	"http": {
	  "method": "GET",
	  "path": "/",
	  "protocol": "HTTP/1.1",
	  "sourceIp": "116.14.157.253",
	  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
	},
	"requestId": "2fbff872-ba4e-4b6d-8753-73fc93aa0620",
	"routeKey": "$default",
	"stage": "$default",
	"time": "16/Jul/2023:08:10:45 +0000",
	"timeEpoch": 1689495045499
  },
  "isBase64Encoded": false
}
